### ISSUE TITLE
Missed regression

### ISSUE THREAD

**Issue by Fraser999** [brson/taskcluster-crater#4]
When running crater against [#36384](https://github.com/rust-lang/rust/pull/36384), the [results exposed a regression in our `XorName` crate](https://github.com/rust-lang/rust/issues/36830#issuecomment-252168923).

This crate has been absorbed (more or less verbatim) into our Routing crate which is published on crates.io, and as such I'd have expected a similar regression to have been exposed at https://github.com/maidsafe/routing/blob/master/src/xor_name.rs#L58-L59.

**Comment by bluss** [comment]
@Fraser999 The new code will not stop compiling and will not regress because of a minute difference.

The orignal in XorName uses `[u8; 64]`, and the new code uses `[u8; 32]`. Arrays of size 0-32 inclusive have the needed explicit trait implementations, including Eq.

**Comment by Fraser999** [comment]
Ah - of course!  Sorry for the bogus report :(
